# Generated by Django 5.2.4 on 2025-07-13 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggestedSchedule',
            new_name='GeneratedPlan',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RenameField(
            model_name='generatedplan',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CLASS', 'Class'), ('WORK', 'Work'), ('EXERCISE', 'Exercise'), ('PERSONAL', 'Personal'), ('SLEEP', 'Sleep'), ('STUDY', 'Study'), ('SOCIAL', 'Social')], max_length=50)),
                ('duration_hours', models.FloatField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours_per_week', models.IntegerField(default=20)),
                ('class_hours_per_week', models.IntegerField(default=15)),
                ('sleep_target_hours', models.FloatField(default=8.0)),
                ('workout_target_hours', models.FloatField(default=3.0)),
                ('other_commitments', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
